# Site settings
title: Corey Klevan
description: Jekyll Theme Minimal Resume
baseurl: "coreyklevan.github.io" # the subpath of your site, e.g. /blog
url: "coreyklevan.ml" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Corey Klevan
user_description: I'm a Computer Science Major at Arcadia University, always searching for the next challenge; no task is too scary nor too difficult. Lately I have been immersed in world of Giving Circles working with Grapevine, a California based startup trying to improve the world through collaborative giving. I'm the first engineer they hired to work on the platform.
user_title: Student/Software Engineer
email: coreyklevan@gmail.com
# twitter_username: lorem_ipsum
instagram_username: theklevanator
facebook_username: corey.klevan
linkedin_username: corey-klevan
github_username:  coreyklevan
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

#exclude: ['package.json', 'src' , 'node_modules']
